version: '3.8'
services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    depends_on:
      - db
    ports:
      - "9000:9000"  # PHP-FPM exposto na porta 9000
    container_name: laravel-php
    volumes:
      - ./src:/var/www
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8079:80"
    volumes:
      - ./src:/var/www
      - ./nginx.conf:/etc/nginx/nginx.conf  # Arquivo principal
      - ./default.conf:/etc/nginx/conf.d/default.conf  # Configuração do servidor
    depends_on:
      - php
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: laravel-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gerenciamento_de_tarefas
    ports:
      - "3307:3306"
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  
networks:
  app-network:
    driver: bridge
